import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import React, { useEffect } from 'react';
import productApi from '../api/productsApi';
import MainLayout from '@/components/Layout';


export default function Home() {

  useEffect(() => {
    productApi.getAll()
      .then(response => console.log(response)); // test axios
  })
  
  return (
    <>
      <Head>
        <title>Ecommerce Proxy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div>
          Main content here....
        </div>
      </MainLayout>
    </>
  )
}
